name: Format

on: [push, pull_request]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run formatter check
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed --length 120"
