name: Format

on: [push, pull_request]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run formatter check
        id: checkstyle
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"
      - name: Check if formatter failed
        if: steps.checkstyle.ouputs.exit_code == -1
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: '**The Java checkstyle failed.**\n\nPlease run `mvn googleformatter:format@reformat-sources` in the root of your repository and commit the changes to this PR. You can also use [pre-commit](https://pre-commit.com/) to automate the Java code formatting.'
              });
